apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  name: D3p0t-Auth-Module
  description: An example deployment of a Backstage application.
  annotations:
      github.com/project-slug: 'd3p0t/auth-module'
      backstage.io/techdocs-ref: dir:.
  tags:
    - php
    - d3p0t
    - library
spec:
  type: library
  owner: D3p0t
  lifecycle: experimental
  dependsOn:
    - component:d3p0t-core
